### ISSUE TITLE
Water pipes and other networks such as the ferry tool can't be placed directly from building to building without anarchy active.

### ISSUE THREAD

**Issue by Leo512bit** [Quboid/NetworkAnarchy#11]
See: https://github.com/algernon-A/EightyOne2/issues/3

**Comment by Quboid** [comment]
Thank you, I believe I have identified the issue. Can you confirm that this only happens when Straight Slope is on?

**Comment by Leo512bit** [comment]
No, it also happens when Straight Slope is off.
