### ISSUE TITLE
Mod doesn't appear in Content Manager after local download

### ISSUE THREAD

**Issue by jahodovykolac** [Quboid/NetworkAnarchy#20]
So, I'm a poor Epic user, so I don't have Workshop available. Recently I found out that you can download most mods from GitHub and manually put them in the folder. I tried it, and it works. Or, mostly. This mod unfortunately doesn't appear in the Content Manager. I've probably just done something wrong, but here is what I've done:
Downloaded the .zip (I've tried both master and last release)
Extract it
Move the folder to (Install location)/CitiesSkylines/Files/Mods
Run the game.
And yes, I have Harmony installed. Other mods depending on Harmony work fine

**Comment by Quboid** [comment]
I don't know if this works the same way for the Epic version, but for Steam on Windows the mod folder needs to go into the %localappdata%\Colossal Order\Cities_Skylines\Addons\Mods folder

**Comment by jahodovykolac** [comment]
Unfortunately I think this is not the problem. I've heard the folders don't matter, but with another mod, the problem was that the mod had to have some Epic-specific binaries. The author provided these on their Discord server (which I don't have).
